namespace: identomat-test

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    #    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "identomat-notifications"
    nginx.org/websocket-services: "identomat-notifications"
    nginx.ingress.kubernetes.io/affinity: cookie
  hosts:
    - host: notifications.test.identomat.com
      paths:
        - path: /
          backend:
            serviceName: identomat-notifications
            servicePort: http

monitoring:
  enabled: true
