apiVersion: v1
kind: Service
metadata:
    name: {{ include "identomat-notifications.fullname" . }}
    namespace: {{ .Values.namespace }}
    labels:
        app.kubernetes.io/name: {{ include "identomat-notifications.name" . }}
spec:
    type: {{ .Values.service.type }}
    ports:
        - port: {{ .Values.service.http.port }}
          targetPort: 3000
          protocol: TCP
          name: http
    selector:
        app.kubernetes.io/name: {{ include "identomat-notifications.name" . }}
